server:
  port: 8082 # Porta diferente

spring:
  application:
    name: order-service # Nome para registrar no Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/